stages:
    - test
    - build
    
test:
    stage: test
    image: maven:latest
    script:
        - mvn clean test
        
build:
    stage: build
    image: maven:latest
    script:
        - mvn clean verify
    artifacts:
        paths:
            - target